Add 60 FPS mode
LostArtefacts/TRX pull request #1177
Opened 2024-03-21 13:08 UTC by rr-

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Uses similar technique to the remasters, where rather than reworking the entire game logic to use different values, we interpolate things drawn on screen every other frame – specifically item positions and animations.

It is essential to avoid interpolating differences when using this technique. For instance, after Lara finishes pushing a movable block, it should instantly move to its new position since the object is being moved by a whole block in one frame (the push animation is relative to the block's original placement, which remains unchanged until the movement is complete). Likewise, when Lara climbs stairs and 1-click surfaces, it's important to move her upward immediately, as interpolating her vertical position change looks weird. To that end, we limit interpolating to scenarios only when the item position deltas are small enough. This seems to be working OK.

Nonetheless there are several known pain points as the PR is more of a proof of concept rather than a final solution:

- Hair is 30 FPS
- Shadows are 30 FPS
- Camera during Lara's roll animation is shaky
- There seems to be more black camera moments
- Combat camera lags
- Passport opening / closing animations have low FPS

Despite the above issues, I believe that this already brings significant value and can be merged as-is, whereas the problems can be addressed in subsequent tasks.

Before merging I would like to land #1173 first as there's some overlap and Mac builds are definitely more polished.

2024-03-23 12:06 UTC, rr- commented
Rebased onto newest mac build

2024-03-23 13:04 UTC, Richard-L commented
@rr- walkaway shared a test build. It's glorious...!

Started collecting things I noticed in a list that is growing quickly, yet mostly small things.

Should I post it here or discord? Some things might be useful to look at with video comparisons to OG 30fps. Is it too much to go in here?

2024-03-23 16:57 UTC, rr- commented
@Richard-L let's post them here.

2024-03-23 22:41 UTC, walkawayy commented
Things I've noticed so far:

30 FPS camera or laggy camera:
* During roll
* When Lara jumps and is reaching out to grab
* In combat camera when bounced around level geometry in the way (?), can test by holding out guns and running around the one square block pillar at the beginning of Vilcabamba
* When Lara gets grabbed by the abortion monster
* Jump forward or backward and do a jump twist, camera seems choppy when rotating behind Lara

Flickers (wrong anim interpolation maybe?):
* I think any transition to freefall seems to flicker (backflip, forward jump)

30 FPS:
* Lara's braid
* Passport opening / closing animation

2024-03-23 22:53 UTC, Richard-L commented
More 30 fps (maybe intentional):
- pickup 3d animation
- Lava emitters
- Dart projectiles

2024-03-23 22:56 UTC, Richard-L commented
https://github.com/LostArtefacts/TR1X/assets/4934209/2e7e1e63-fd0e-4f6c-a2d3-7f43878161d6


https://github.com/LostArtefacts/TR1X/assets/4934209/3782ccd9-aed4-417e-86ff-bf2ede2d69eb

- Some of the rooms seem to flicker black very briefly in some instances.
- Lara's arms are black in OBS recordings. They look correct in-game.

2024-03-23 23:04 UTC, Richard-L commented
The demos of Vilcabamba and Lost Valley are desynced. Not by much, but noticeably.

2024-03-24 08:11 UTC, aredfan commented
I've noticed these water issues from the TR1X_60_FPS_v1 build: 

- The shimmering is gone.
- The wobbly effect only reacts to Lara's camera movements.  If the camera remain still then no wobbly effect.  This happens above and below the water level.

2024-03-24 22:30 UTC, rr- commented
I fixed the water effects as well as texture animations. Furthermore I've added `/fps 60` `/fps 30` command. Demos look fine to me.

2024-03-24 23:35 UTC, walkawayy commented
Demos look fine to me on latest code.

Ste reported:
```
I played a little. The game runs well. I don't notice a drop in framerate. On the other hand, Lara's braid doesn't work well in 60fsp but I imagine you already know that. The camera jerks a little when it quickly finds itself behind Lara, I noticed too.
( I play in 2560 x 1600 - i7 13th & 4070 rtx)
Bats' falling animations jump a bit (unlike wolves, their death animations are perfect). The sprites of the smoke from the arrows on the wall look ugly at 60 fps, but the game is like that
```

2024-03-25 12:07 UTC, aredfan commented
I found an issue with darts either becoming stuck or invisible, this doesn't happen in 3.1.1.

I'm not sure how to reliably reproduce this bug so I included a link to my video, which can be played on the browser.

https://drive.google.com/drive/folders/1x0nVXj9sLTe3EXbOERmXINlQmkcP5_X6?usp=sharing

2024-03-25 19:23 UTC, aredfan commented
Just a couple more things to report:

- Scrolling through saves is twice as fast in 60fps mode.
- In some fixed-camera positions, there's a subtle shift in the first 2 frames that isn't present in 30fps mode. #1186

2024-03-25 23:58 UTC, walkawayy commented
New build seems great!

Darts seem good now. The jump and grab stutter seems to be gone. The roll looks really nice. And the Lara freefall transition stuttering also seems gone.

2024-03-26 08:15 UTC, Richard-L commented
New build fixed a lot of the camera hitching, maybe all of it 👌

Only one stutter in the roll remains.

And I'm not sure this is relevant, but some animations seem to spasm a bit after you use the Tab key twice to speed up the game, for example the swim animation.

2024-03-26 12:31 UTC, aredfan commented
Most of my issues are resolved in the TR1X_60FPS_v2 build.  Thank you for the speed in getting this done.

I also understand the camera shifts issue isn't possible to fix so I'll consider it resolved.  I trust your judgement. 👍 

There's one more issue remaining - if you disable EDIOS logo then all graphic images including loading screens and credits are also disabled.

2024-03-26 20:07 UTC, rr- commented
@aredfan @Richard-L @walkawayy  can we log all of the still standing or newly found issues as new issues? Tracking what got fixed and what not started to get out of hand. I've created a special label for the tickets that address issues on not-yet merged things.

2024-03-26 20:13 UTC, walkawayy commented
> @aredfan @Richard-L @walkawayy can we log all of the still standing or newly found issues as new issues? Tracking what got fixed and what not started to get out of hand. I've created a special label for the tickets that address issues on not-yet merged things.

Sure. aredfan has been making issues. I wasn't sure if you preferred them all in this PR or as multiple tasks in a single `60 FPS` issue. I will try to open an outstanding issues from this thread.

2024-03-27 11:47 UTC, aredfan commented
**Clock in all 4 scenarios:** LGTM

**Animated textures:** LGTM

2024-03-30 21:05 UTC, lahm86 commented
@rr- re #1192, the diff below appears to fix this. So we ensure that `g_Camera.pos.room_number` is correct before it's referenced in `Room_DrawAllRooms`.

It doesn't completely resolve the other issues mentioned in #1034, but in those cases I believe the camera is going into the wall so it's slightly different. I'm still working on that separately.

```diff
diff --git a/src/game/camera.c b/src/game/camera.c
index 243d6f2b..16d43ae7 100644
--- a/src/game/camera.c
+++ b/src/game/camera.c
@@ -840,6 +840,11 @@ void Camera_MoveManual(void)
 
 void Camera_Apply(void)
 {
+    Room_GetFloor(
+        g_Camera.interp.result.pos.x,
+        g_Camera.interp.result.pos.y + g_Camera.interp.result.shift,
+        g_Camera.interp.result.pos.z,
+        &g_Camera.pos.room_number);
     Matrix_LookAt(
         g_Camera.interp.result.pos.x,
         g_Camera.interp.result.pos.y + g_Camera.interp.result.shift,
```

2024-03-31 22:10 UTC, rr- commented
@lahm86 @walkawayy this is ready for a re-review.

2024-04-01 00:14 UTC, walkawayy commented
Is the plan to merge and potentially fix some bugs later? I'm OK with that, but I am just wondering for the review process.

From what I tested, everything plays really nicely. All the open `Unreleased` issues still seem to apply except #1192 does appear to be fixed which is great. I think it can be closed. The other open issues I notice are still happening.

2024-04-01 05:38 UTC, rr- commented
@walkawayy I'd like to merge it in the current form as it no longer seems to introduce bugs, only needs improvements in some places (eg stuff being still 30 fps) that I think are ok to be provided at a later time. Thanks

2024-04-01 14:28 UTC, walkawayy requested changes
Reposting from Discord that there is an issue with the passport exit to title crashing the game. `it has to do with the fix for camera – we're trying to use room data after it's gone. should be a simple fix`

I didn't notice any other issues during my testing last night.

2024-04-01 15:05 UTC, rr- commented
@walkawayy this is now fixed. Thanks

2024-04-01 20:23 UTC, lahm86 commented
Really fantastic 🚀 

The only thing I thought of for now was to enforce the FPS value in `config.c` to either 30 or 60. Currently you can edit the json file and it creates some interesting results, so probably an idea to ensure it's set to the supported values.

Other than this and the centaur issue, I'm ready to hit approve.

2024-04-01 20:47 UTC, rr- commented
Fixed the centaur issue as well as added sanitization of FPS values.

2024-04-01 21:22 UTC, walkawayy approved these changes
LGTM!!!

2024-04-01 21:28 UTC, aredfan commented
Centaur fix - LGTM 👍

2024-04-01 21:36 UTC, lahm86 approved these changes

2024-04-01 21:39 UTC, merged