libtrx/config: support enforced config settings
LostArtefacts/TRX pull request #1854
Opened 2024-11-09 17:33 UTC by lahm86

Resolves #1846.
Resolves #1847.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This allows an enforced object to be defined in the config file, within which any regular config setting can be defined, and the values from here will be enforced in the game. This applies to TR1 and TR2.

Example snippet for `TR1X.json5`:
```json
{
  "enable_uw_roll" : true,
  "enforced" : {
    "enable_uw_roll" : false
  }
}
```
Here the initial value is replaced by the one in the `enforced` object when the game loads. When the game writes back the config, both entries will be preserved, meaning if players want to remove these enforcements they can do so and their original settings will not need to be re-edited.

The config tool will grey out any enforced options, and display a message so the user knows why they cannot be edited.

I think we can remove `force_game_modes` and `force_save_crystals` from the gameflow and allow builders to implement it in the same way as above. But probably best handled in its own PR and after review/testing of this one.

Re #1847, this same approach can be used by builders to remove features available only with Lara's animation injection. The alternative to this is testing animation goals, which IMO would result in too many additional code checks for animation goals.

2024-11-09 18:49 UTC, aredfan approved these changes

2024-11-09 19:18 UTC, walkawayy requested changes
I think everything looks good and works well!

My one suggestion is to change how the config tool shows the enforced option. Right now, the tool shows the user's option greyed out. However, I think the tool should show the enforced option greyed out. For example, using your example force disables the underwater roll:
```
  "enforced" : {
    "enable_uw_roll" : false
  }
```

And that is enforced in game so I can't roll. But the config tool's greyed out option makes it seem like the author force enabled the underwater roll as seen here:

![image](https://github.com/user-attachments/assets/689db2ed-7c46-4bf9-a093-9f83865424b6)

2024-11-09 21:12 UTC, lahm86 commented
Pushed an update @walkawayy. Unfortunately, because of the abstraction in how the properties are managed, I couldn't think of a good way to store the enforced value but retain writing the actual value back when needed. But I agree it's clearer to show what's actually in place, so let me know if you think the update is OK. It just shows the raw enforced value along with a message. It's clear there is no UI input as such.

2024-11-09 21:32 UTC, walkawayy commented
Hm it still seems to show the wrong option for me:
![image](https://github.com/user-attachments/assets/1e6126d9-2d78-48e5-8ba8-91d87a426570)

2024-11-09 21:34 UTC, lahm86 commented
Should show like this - maybe you're running the wrong download?
![image](https://github.com/user-attachments/assets/c6400772-49b3-47fc-9092-98511f3979a1)

2024-11-09 21:37 UTC, walkawayy commented
Oh oops I didn't notice I had to do a git pull with a rebase. Yes it works perfectly now.

2024-11-09 21:37 UTC, walkawayy approved these changes

2024-11-09 23:21 UTC, rr- reviewed
Looks good but we need to describe this mechanism in the gameflow docs for it to be adopted.

2024-11-10 10:42 UTC, lahm86 commented
Updated `GAMEFLOW.md` with some details on this. I've used save crystals as an example, although I'd still like to remove the other dedicated options for enforcing that and game modes in a separate PR. I'll update the gameflow doc again there as we mention those forced variables at the top of that document.

2024-11-10 15:31 UTC, rr- approved these changes

2024-11-10 17:13 UTC, merged