data: fix Larson's gun textures
LostArtefacts/TRX pull request #740
Opened 2023-02-24 15:02 UTC by lahm86

Resolves #737.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Larson's gun in Tomb of Qualopec will now match the cutscene that follows, as well as Sanctuary of the Scion.

![20230224_144104_Tomb_of_Qualopec](https://user-images.githubusercontent.com/33758420/221211051-d3c01b92-0fbf-46e3-bed8-67a35082ba5a.jpg)

2023-02-24 17:47 UTC, walkawayy requested changes
LGTM.

2023-02-24 17:47 UTC, walkawayy approved these changes

2023-03-01 20:30 UTC, rr- approved these changes

2023-03-09 11:10 UTC, lahm86 commented
I fixed a merge conflict in the changelog. Could you double check that it's OK @rr- before I merge?

2023-03-09 12:17 UTC, rr- approved these changes
LGTM

2023-03-09 12:40 UTC, merged