lara_look: refactor all looks to use the correct functions
LostArtefacts/TRX pull request #817
Opened 2023-04-25 19:39 UTC by walkawayy

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Refactor all looks to use the generic functions. Prep for inverted look #816.
...

2023-04-25 19:44 UTC, walkawayy commented on src/game/lara/lara_state.c
> +        Lara_LookLeftRight(MAX_HEAD_ROTATION_SURF, HEAD_TURN_SURF);
Ah yes I see `g_Lara.head_y_rot -= HEAD_TURN_SURF;` vs `g_Lara.head_y_rot -= HEAD_TURN / 2;`. I'll fix.

2023-04-25 20:28 UTC, walkawayy commented
I added separate look functions for when Lara treads on the surface.

2023-04-26 18:40 UTC, rr- reviewed
To avoid using `MAX_HEAD_ROTATION` / `HEAD_TURN` everywhere and reduce introduced code duplication, could we name `Lara_LookLeftRight` `Lara_LookLeftRightBase` and have two functions, `Lara_LookLeftRightSurface` and `Lara_LookLeftRightUW` that pass proper constants to `Lara_LookLeftRightBase`? The division by 2 should happen in the wrapper functions and not in the base function.

(and the same for `Lara_LookUpDown()`.)

2023-04-27 04:21 UTC, walkawayy commented
Lmk what you think of the latest push. I added `Lara_LookLeftRightBase` and `Lara_LookUpDownBase`. I only added `Lara_LookLeftRightSurface` and `Lara_LookUpDownSurface` as special wrappers because Lara treading on the surface is the only unique look case as far as I can tell. Lara out of water and Lara under the water share the same look calls.

2023-04-27 08:17 UTC, rr- reviewed
You left the division by 2 in the base function for the head turn – it should be moved to `LeftRight(void)`, otherwise Lara moves her head too slowly on the surface.

Upon seeing it I think naming the function `Surf` and not `Surface` would be better for now, not to introduce new nomenclature in the code.

2023-04-27 14:12 UTC, walkawayy commented
Ah sorry about that. I should not commit when tired. I think it should be good now? Sorry for the confusion.

2023-04-27 15:39 UTC, rr- requested changes

2023-04-27 15:39 UTC, rr- commented on src/game/lara/lara_look.c
> +            g_Lara.head_y_rot -= head_turn / 2;
Please remove `/ 2` here.

2023-04-30 11:04 UTC, rr- approved these changes
LGTM. Final question – does Lara turn her torso around when she's in the STOP state and has her pistols equipped? Did she use to prior to this patch?

(When merging, please squash the commits.)

2023-05-01 00:58 UTC, walkawayy commented
Seems ok to me?

TombATI:
![image](https://user-images.githubusercontent.com/81546780/235384918-4d5bfd62-e374-40cb-b50f-e582a1196bd0.png)

T1M Look Refactor:
![20230430_205738_Caves](https://user-images.githubusercontent.com/81546780/235384955-525a5592-bd08-414c-a9a5-d847461fba72.jpg)

2023-05-01 08:39 UTC, rr- commented
Let's merge

2023-05-01 13:24 UTC, merged